name: simpletest
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/simpletest.yml'

jobs:
  x86_64_simpledocker:
    runs-on: ubuntu-latest
    steps:    
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        touch hello.world
        echo "hh" >> hello.world
        mkdir ~/.ssh/
        curl -fsSL https://raw.githubusercontent.com/linhailan/myActions/master/x86_64/ssh.config > ~/.ssh/config
        echo ${KNOWN_HOSTS} >> ~/.ssh/known_hosts
        echo ${TEST} > ~/.ssh/pear_id_rsa
        rsync -P hello.world hktest:/tmp/
