name: simpledocker
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/simpledocker.yml'
      - 'simpledocker/**'
      - '!simpledocker/README.md'

jobs:
  x86_64_simpledocker:
    runs-on: ubuntu-latest
    steps:    
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff /swapfile
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        docker rmi `docker images -q`
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo df -h
        curl -fsSL https://raw.githubusercontent.com/linhailan/myActions/master/.bashrc >> ~/.bashrc
        sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        touch hello.world
        echo "hh" >> hello.world
        mkdir ~/.ssh/
        curl -fsSL https://raw.githubusercontent.com/linhailan/myActions/master/x86_64/ssh.config > ~/.ssh/config
        echo ${KNOWN_HOSTS} >> ~/.ssh/known_hosts
        echo ${TEST} > ~/.ssh/pear_id_rsa
        rsync -P hello.world hktest:/tmp/
