name: simpletest
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/simpletest.yml'

jobs:
  x86_64_simpledocker:
    runs-on: ubuntu-latest
    steps:    
    - name: Prepare environment.
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt install rsync
        touch hello.world
        echo "hh" >> hello.world
        mkdir ~/.ssh/
        curl -fsSL https://raw.githubusercontent.com/linhailan/myActions/master/x86_64/ssh.config > ~/.ssh/config
        cat ~/.ssh/config

        echo ${{ secrets.KNOWN_HOSTS }} >> ~/.ssh/known_hosts
        cat ~/.ssh/known_hosts

        echo ${{ secrets.TEST }} > ~/.ssh/pear_id_rsa
        ls -alt ~/.ssh/pear_id_rsa
        chmod 600 ~/.ssh/pear_id_rsa

        scp ./hello.world hktest:/tmp/hello.1
        rsync -P ./hello.world hktest:/tmp/hello.2
